baseURL = "https://wright-development.github.io/"
languageCode = "en-us"
title = "Expected.Request"
theme = "blackburn"
copyright = "Wright Development &copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
    subtitle = "Simple API Testing"
    googleanalytics = "UA-61721549-2"
    highlightjs = "tomorrow-night-eighties"
    highlightjs_extra_languages = ["yaml", "dockerfile"]
    dateFormat = "02 January 2006"

[params.author]
    firstName = "Darrius"
    lastName = "Wright"
    gender = "male"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Request"
    weight = 2
    identifier = "request"
    url = "/api/request/"
  [[menu.main]]
    name = "Expect"
    weight = 3
    identifier = "expect"
    url = "/api/expect-request/"
  [[menu.main]]
    name = "Done"
    weight = 4
    identifier = "done"
    url = "/api/done-request/"
  [[menu.main]]
    name = "ContentConverter"
    weight = 5
    identifier = "content"
    url = "/api/content-converter/"
  [[menu.main]]
    name = "View On GitHub"
    weight = 6
    identifier = "project"
    url = "https://github.com/wright-development/Expected.Request"

[social]
  github = "wright-development"
  linkedin = "darrius-wright"
  twitter = "develop_wright"